export default {
  vastmanland: { name: 'Västmanlands län', status: 0.1 },
  blekinge: { name: 'Blekinge län', status: 0.1 },
  ostergotland: { name: 'Östergötlands län', status: 0.8 },
  uppsala: { name: 'Uppsala län', status: 0.1 },
  skane: { name: 'Skåne län', status: 0.2 },
  gavleborg: { name: 'Gävleborgs län', status: 0.1 },
  jamtland: { name: 'Jämtlands län', status: 1 },
  jamtland2: { name: 'Jämtlands län', status: 0.6 },
  norrbotten: { name: 'Norrbottens län', status: 0.3 },
  stockholm: { name: 'Stockholms län', status: 1.0 },
  sodermanland: { name: 'Södermanlands län', status: 0.1 },
  kronoberg: { name: 'Kronobergs län', status: 0.1 },
  halland: { name: 'Hallands län', status: 0.7 },
  vasternorrland: { name: 'Västernorrlands län', status: 0.1 },
  vastragotaland: { name: 'Västra götalands län', status: 0.5 },
  gotland: { name: 'Gotlands län', status: 0.1 },
  kalmar: { name: 'Kalmar län', status: 0.9 },
  dalarna: { name: 'Dalarnas län', status: 0.1 },
  vasterbotten: { name: 'Västerbottens län', status: 0.1 },
  vasterbotten2: { name: 'Västerbottens län', status: 0.2 },
  varmland: { name: 'Värmlands län', status: 0.5 },
  jonkoping: { name: 'Jönköpings län', status: 0.4 },
  jonkopng2: { name: 'Jönköpings län', status: 0.1 },
  orebro: { name: 'Örebro län', status: 0.3 },
};

